version: 2.1
defaults: &default
  docker:
    - image: cimg/node:18.4.0
jobs:
  build:
    <<: *default
    steps:
      - checkout
      - run:  npm run lint
  test:
    <<: *default
    steps:
      - checkout
      - run:  npm run test
  analyze:
    <<: *default
    steps:
      - checkout
      - run:  npm run audit

workflows:
  default:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
