version: 2.1
defaults: &defaults
  docker:
    - image: cimg/node:18.4.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - run: npm run test
  analyze:
    <<: *defaults
    steps:
      - checkout
      - run: npm run audit

workflows:
  my_wf:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
